[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"

[headers]
  [[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer-when-downgrade"
